import { View, Text, TextInput, Pressable, Alert } from "react-native";
import { Link,router  } from "expo-router";
import { useState } from "react";
import { registerUser } from "../../api/userApi"
import { saveUserId } from "../../utils/storage";

export default function RegisterScreen() {

  const [email, setEmail] = useState("")
  const [phone, setPhone] = useState("")
  const [password, setPassword] = useState("")
  
  const handleRegister = async () => {
    try {
      const user = await registerUser({ email, phone, password })
      await saveUserId(user.id)//generated by jpa
      router.push("/(auth)/verification")
    } catch (e:any) {
      Alert.alert("Error", e.message);
    }
  }


  return (
    <View style={{ flex: 1, padding: 20, justifyContent: "center" }}>
      <Text style={{ fontSize: 24, marginBottom: 20 }}>Register</Text>


      <TextInput
        placeholder="Email"
        value={email}
        onChangeText={setEmail}
        style={{ borderWidth: 1, padding: 10, marginBottom: 10 }}
          />
          
      <TextInput
        placeholder="Mobile Number"
        value={phone}
        onChangeText={setPhone}
        style={{ borderWidth: 1, padding: 10, marginBottom: 10 }}
      />

      <TextInput
        placeholder="Password"
        secureTextEntry
        value={password}
        onChangeText={setPassword}
        style={{ borderWidth: 1, padding: 10, marginBottom: 20 }}
      />

      <Pressable
         onPress={handleRegister}
        style={{ backgroundColor: "#8B0000", padding: 12, borderRadius: 6 }}
      >
        <Text style={{ color: "white", textAlign: "center" }}>Register</Text>
      </Pressable>
    </View>
  );
}
